In [1]:
import pandas as pd
from pandas import json_normalize
import json
import numpy as np
import ast

In [4]:
df = pd.read_csv('data_movies_fin.csv')
df.head()

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,...,tagline,title,vote_average,vote_count,id_btc,name_btc,genero_id,genero_nombre,release_year,return
0,30000000.0,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar Animation Studios,United States of America,1995-10-30,373554033,81,...,NaN,Toy Story,7.7,5415.0,10194.0,Toy Story Collection,16.0,Animation,1995,12.45
1,65000000.0,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,TriStar Pictures,United States of America,1995-12-15,262797249,104,...,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,NaN,NaN,35.0,Comedy,1995,4.04
2,0.0,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,Warner Bros.,United States of America,1995-12-22,0,101,...,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,119050.0,Grumpy Old Men Collection,10751.0,Family,1995,0.00
3,16000000.0,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156,127,...,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,NaN,NaN,12.0,Adventure,1995,5.09
4,0.0,11862.0,en,Just when George Banks has recovered from his ...,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911,106,...,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,96871.0,Father of the Bride Collection,14.0,Fantasy,1995,0.00

In [5]:
#Convertir los valores de id en entero ya que asÃ­ estaban en el data credits
df['id'] = df['id'].astype(int)
df.head()

In [7]:
df_peliculas = df
df_creditos = pd.read_csv('creditos_fin.csv')

In [8]:
df_unido = pd.merge(df_peliculas, df_creditos, on='id')

In [16]:
df_unido.head()

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,...,vote_count,id_btc,name_btc,genero_id,genero_nombre,release_year,return,character_cast,name_cast,name_crew
0,30000000.0,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar Animation Studios,United States of America,1995-10-30,373554033,81,...,5415.0,10194.0,Toy Story Collection,16.0,Animation,1995,12.45,"'Woody (voice)', 'Buzz Lightyear (voice)', 'Mr...","'Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim ...","'John Lasseter', 'Joss Whedon', 'Andrew Stanto..."
1,65000000.0,8844,en,When siblings Judy and Peter discover an encha...,17.015539,TriStar Pictures,United States of America,1995-12-15,262797249,104,...,2413.0,NaN,NaN,35.0,Comedy,1995,4.04,"'Alan Parrish', 'Samuel Alan Parrish / Van Pel...","'Robin Williams', 'Jonathan Hyde', 'Kirsten Du...","'Larry J. Franco', 'Jonathan Hensleigh', 'Jame..."
2,0.0,15602,en,A family wedding reignites the ancient feud be...,11.712900,Warner Bros.,United States of America,1995-12-22,0,101,...,92.0,119050.0,Grumpy Old Men Collection,10751.0,Family,1995,0.00,"'Max Goldman', 'John Gustafson', 'Ariel Gustaf...","'Walter Matthau', 'Jack Lemmon', 'Ann-Margret'...","'Howard Deutch', 'Mark Steven Johnson', 'Mark ..."
3,16000000.0,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156,127,...,34.0,NaN,NaN,12.0,Adventure,1995,5.09,"""Savannah 'Vannah' Jackson"", ""Bernadine 'Berni...","'Whitney Houston', 'Angela Bassett', 'Loretta ...","'Forest Whitaker', 'Ronald Bass', 'Ronald Bass..."
4,0.0,11862,en,Just when George Banks has recovered from his ...,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911,106,...,173.0,96871.0,Father of the Bride Collection,14.0,Fantasy,1995,0.00,"'George Banks', 'Nina Banks', 'Franck Eggelhof...","'Steve Martin', 'Diane Keaton', 'Martin Short'...","'Alan Silvestri', 'Elliot Davis', 'Nancy Meyer..."

In [26]:
# FunciÃ³n para devolver la cantidad de pelÃ­culas en un mes especÃ­fico

def cantidad_filmaciones_mes(mes):
    # Convertir la columna "release_date" a tipo datetime si no estÃ¡ en ese formato
    df_unido['release_date'] = pd.to_datetime(df_unido['release_date'])
    # Filtrar los datos por el mes especificado en espaÃ±ol
    data_filtrado = df_unido[df_unido['release_date'].dt.month_name(
        locale='es') == mes]
    # Obtener la cantidad de registros que coinciden
    cantidad = len(data_filtrado)
    return cantidad

In [28]:
# uso de la funciÃ³n del mes
cantidad_depelis = cantidad_filmaciones_mes('Diciembre')
print(f"La cantidad de pelÃ­culas estrenadas en el mes es {cantidad_depelis}")

La cantidad de pelÃ­culas estrenadas en el mes es 3798

In [31]:
# FunciÃ³n para devolver la cantidad de pelÃ­culas en un dÃ¬a especÃ­fico

def cantidad_filmaciones_dia(dia):
    # Filtrar los datos por el dÃ­a de la semana especificado en espaÃ±ol
    data_filtrado = df_unido[df_unido['release_date'].dt.day_name(
        locale='es') == dia]
    # Obtener la cantidad de registros que coinciden
    cantidad = len(data_filtrado)
    return cantidad

In [32]:
# uso de la funciÃ³n del dÃ­a
cantidad_dia = cantidad_filmaciones_dia('Martes')
print(f"La cantidad de pelÃ­culas estrenadas en el dÃ¬a es {cantidad_dia}")

La cantidad de pelÃ­culas estrenadas en el dÃ¬a es 4644

In [35]:
# consulta del score con el aÃ±o de la pelÃ­cula

def score_titulo(title):
    # Reemplaza 'tu_archivo.csv' con el nombre de tu archivo de datos
    pelicula = df_unido[df_unido['title'] == title]
    if pelicula.empty:
        return "No se encontrÃ³ informaciÃ³n para la pelÃ­cula: " + title
    else:
        release_year = pelicula['release_year'].values[0]
        score = pelicula['popularity'].values[0]
        return f"La pelÃ­cula '{title}' fue estrenada en el aÃ±o {release_year} y tiene un puntaje de {score}"

In [36]:
# Ejemplo de uso:
resultado = score_titulo('Toy Story')
print(resultado)

La pelÃ­cula 'Toy Story' fue estrenada en el aÃ±o 1995 y tiene un puntaje de 21.946943

In [37]:
#FunciÃ³n para datos de votos por pelÃ­cula 
def votos_titulo(titulo_de_la_filmacion):
    data = df_unido
    pelicula = data[data['title'] == titulo_de_la_filmacion]
    if pelicula.empty:
        return "No se encontrÃ³ informaciÃ³n para la pelÃ­cula: " + titulo_de_la_filmacion
    else:
        votos = pelicula['vote_count'].values[0]
        promedio = pelicula['vote_average'].values[0]
        if votos >= 2000:
            return f"La pelÃ­cula '{titulo_de_la_filmacion}' fue estrenada en el aÃ±o {pelicula['release_year'].values[0]}. La misma cuenta con un total de {votos} valoraciones, con un promedio de {promedio}"
        else:
            return f"La pelÃ­cula '{titulo_de_la_filmacion}' no cumple con la condiciÃ³n de tener al menos 2000 valoraciones."

In [38]:
resultado = votos_titulo('Toy Story')
print(resultado)

La pelÃ­cula 'Toy Story' fue estrenada en el aÃ±o 1995. La misma cuenta con un total de 5415.0 valoraciones, con un promedio de 7.7

In [19]:
# FunciÃ³n para cÃ¡lculo del actor 

def get_actor(nombre_actor):
    # Leer el dataset que contiene la informaciÃ³n de los actores
    
    # Filtrar los datos por nombre del actor y eliminar duplicados
    lista_peli_actor = df_unido[df_unido['name_cast'].astype(str).str.contains(
        nombre_actor, case=False, na=False)].drop_duplicates(subset='id')
    # Verificar si se encontraron registros para el actor
    if len(lista_peli_actor) > 0:
        # Obtener las pelÃ­culas en las que ha participado el actor
        num_movies = len(lista_peli_actor)
        # Calcular el retorno total para el actor
        total_return = lista_peli_actor['return'].sum()
        # Calcular el promedio de retorno por pelÃ­cula
        average_return = round(total_return / num_movies, 2)
        # Retornar la informaciÃ³n de Ã©xito del actor
        return f"El actor {nombre_actor} ha participado en {num_movies} pelÃ­culas, logrando un retorno total de {total_return} con un promedio de {average_return} por pelÃ­cula."
    else:
        return f"No se encontraron registros para el actor {nombre_actor}."

In [20]:
# Ejemplo de uso
nombre_actor = "Robin Williams"
resultado = get_actor(nombre_actor)
print(resultado)

El actor Robin Williams ha participado en 82 pelÃ­culas, logrando un retorno total de 155.66 con un promedio de 1.9 por pelÃ­cula.

In [21]:
import pandas as pd


def get_director(nombre_director):
    # Read the dataset that contains the movie information
    # Filter the data by director's name and eliminate duplicates
    lista_peli_director = df_unido[df_unido['name_crew'].astype(str).str.contains(
        nombre_director, case=False, na=False)].drop_duplicates(subset='title')
    # Check if any records were found for the director
    if len(lista_peli_director) > 0:
        # Get the movies directed by the director
        movies = lista_peli_director['title'].tolist()
        # Get the release years of the movies
        release_years = lista_peli_director['release_year'].tolist()
        # Get the individual returns of the movies
        returns = lista_peli_director['return'].tolist()
        # Get the budgets of the movies
        budgets = lista_peli_director['budget'].tolist()
        # Get the revenues of the movies
        revenues = lista_peli_director['revenue'].tolist()
        # Return the information for the director
        return list(zip(movies, release_years, returns, budgets, revenues))
    else:
        return f"No records found for the director {nombre_director}."

In [22]:
# Example usage
nombre_director = "Christopher Nolan"
resultado = get_director(nombre_director)
print(resultado)

[('Following', 1998, 8.08, 6000.0, 48482), ('Memento', 2000, 4.41, 9000000.0, 39723096), ('Insomnia', 2002, 2.47, 46000000.0, 113714830), ('Batman Begins', 2005, 2.49, 150000000.0, 374218673), ('The Prestige', 2006, 2.74, 40000000.0, 109676311), ('The Dark Knight', 2008, 5.43, 185000000.0, 1004558444), ('Inception', 2010, 5.16, 160000000.0, 825532764), ('The Dark Knight Rises', 2012, 4.34, 250000000.0, 1084939099), ('Man of Steel', 2013, 2.95, 225000000.0, 662845518), ('Interstellar', 2014, 4.09, 165000000.0, 675120017), ('Transcendence', 2014, 1.03, 100000000.0, 103039258), ('Doodlebug', 1997, 0.0, 0.0, 0), ('Batman v Superman: Dawn of Justice', 2016, 3.49, 250000000.0, 873260194), ('Dunkirk', 2017, 5.2, 100000000.0, 519876949)]